---
name: "Release with submodules"
description: "Create a release and attach a tarball containing source code with submodules"
inputs:
  read-token:
    description: >
      Token (GITHUB_TOKEN or PAT) used to checkout code. Must have
      'contents: read' permissions for all submodules.
    required: false
    default: ${{ github.token }}
  write-token:
    description: >
      Token (GITHUB_TOKEN or PAT) used to manage the release. Requires
      'contents: write' permissions for the calling repository.
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
      name: Check pre-conditions
      uses: actions/github-script@v7
      with:
        script: core.setFailed("Action can only be triggered by tag pushes!")

    - uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}
        submodules: recursive
        token: ${{ inputs.read-token }}

    - name: Create release
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ inputs.write-token }}
        REPONAME: ${{ github.event.repository.name }}
        TAG: ${{ github.ref_name }}
      run: bash "${GITHUB_ACTION_PATH}/action.sh"
